// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_optimize_clusters
IntegerVector rcpp_optimize_clusters(NumericVector bin_vols, NumericVector bin_bads, NumericMatrix monthly_vols, NumericMatrix monthly_bads, double min_vol_ratio, int max_crossings, int max_groups);
RcppExport SEXP _creditools_rcpp_optimize_clusters(SEXP bin_volsSEXP, SEXP bin_badsSEXP, SEXP monthly_volsSEXP, SEXP monthly_badsSEXP, SEXP min_vol_ratioSEXP, SEXP max_crossingsSEXP, SEXP max_groupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type bin_vols(bin_volsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bin_bads(bin_badsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type monthly_vols(monthly_volsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type monthly_bads(monthly_badsSEXP);
    Rcpp::traits::input_parameter< double >::type min_vol_ratio(min_vol_ratioSEXP);
    Rcpp::traits::input_parameter< int >::type max_crossings(max_crossingsSEXP);
    Rcpp::traits::input_parameter< int >::type max_groups(max_groupsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_optimize_clusters(bin_vols, bin_bads, monthly_vols, monthly_bads, min_vol_ratio, max_crossings, max_groups));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_calculate_tier_metrics
List rcpp_calculate_tier_metrics(NumericVector x, IntegerVector groups, IntegerVector defaults, int n_bins);
RcppExport SEXP _creditools_rcpp_calculate_tier_metrics(SEXP xSEXP, SEXP groupsSEXP, SEXP defaultsSEXP, SEXP n_binsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type defaults(defaultsSEXP);
    Rcpp::traits::input_parameter< int >::type n_bins(n_binsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_calculate_tier_metrics(x, groups, defaults, n_bins));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_iv_optimize_clusters
IntegerVector rcpp_iv_optimize_clusters(NumericVector bin_vols, NumericVector bin_bads, NumericMatrix monthly_vols, NumericMatrix monthly_bads, double min_vol_ratio, double lambda_cross, double lambda_vol, int max_bins);
RcppExport SEXP _creditools_rcpp_iv_optimize_clusters(SEXP bin_volsSEXP, SEXP bin_badsSEXP, SEXP monthly_volsSEXP, SEXP monthly_badsSEXP, SEXP min_vol_ratioSEXP, SEXP lambda_crossSEXP, SEXP lambda_volSEXP, SEXP max_binsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type bin_vols(bin_volsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bin_bads(bin_badsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type monthly_vols(monthly_volsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type monthly_bads(monthly_badsSEXP);
    Rcpp::traits::input_parameter< double >::type min_vol_ratio(min_vol_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_cross(lambda_crossSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_vol(lambda_volSEXP);
    Rcpp::traits::input_parameter< int >::type max_bins(max_binsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_iv_optimize_clusters(bin_vols, bin_bads, monthly_vols, monthly_bads, min_vol_ratio, lambda_cross, lambda_vol, max_bins));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_creditools_rcpp_optimize_clusters", (DL_FUNC) &_creditools_rcpp_optimize_clusters, 7},
    {"_creditools_rcpp_calculate_tier_metrics", (DL_FUNC) &_creditools_rcpp_calculate_tier_metrics, 4},
    {"_creditools_rcpp_iv_optimize_clusters", (DL_FUNC) &_creditools_rcpp_iv_optimize_clusters, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_creditools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
