# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_optimize_clusters <- function(bin_vols, bin_bads, monthly_vols, monthly_bads, min_vol_ratio, max_crossings, max_groups) {
    .Call(`_creditools_rcpp_optimize_clusters`, bin_vols, bin_bads, monthly_vols, monthly_bads, min_vol_ratio, max_crossings, max_groups)
}

#' Fast calculation of metrics per tier for a candidate variable
#' 
#' @param x NumericVector candidate variable values
#' @param groups IntegerVector base risk groups (ratings)
#' @param defaults IntegerVector binary target (0/1)
#' @param n_bins int number of bins for discretization
#' @return List of metrics per tier
#' @export
#' @examples
#' \dontrun{
#' x <- runif(100)
#' g <- rep(1:2, each = 50)
#' d <- rbinom(100, 1, 0.1)
#' rcpp_calculate_tier_metrics(x, g, d, 2)
#' }
rcpp_calculate_tier_metrics <- function(x, groups, defaults, n_bins) {
    .Call(`_creditools_rcpp_calculate_tier_metrics`, x, groups, defaults, n_bins)
}

rcpp_iv_optimize_clusters <- function(bin_vols, bin_bads, monthly_vols, monthly_bads, min_vol_ratio, lambda_cross, lambda_vol, max_bins) {
    .Call(`_creditools_rcpp_iv_optimize_clusters`, bin_vols, bin_bads, monthly_vols, monthly_bads, min_vol_ratio, lambda_cross, lambda_vol, max_bins)
}

